version: '3.9'

services:
  utilitysvc:
    image: wiremock/wiremock:latest
    container_name: utilitysvc
    volumes:
      - ./PerfShared/wiremock:/home/wiremock
    ports:
      - 8585:8080
  
  api:
    build:
      context: .
      dockerfile: ResidentApi/Dockerfile
    image: performance/residentapi:latest
    ports:
      - 5294:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Load

  k6:
    build:
      context: .
      dockerfile: PerfShared/k6/Dockerfile
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - MAX_VUS=5
      - BASE_URL=http://host.docker.internal:5294
    image: performance/k6:latest

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./PerfShared/grafana:/etc/grafana/provisioning/